In [29]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd
import tensorflow as tf

# Import our input dataset
attrition_df = pd.read_csv('Resources/HR-Employee-Attrition.csv')
attrition_df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [19]:
# Generate our categorical variable lists
attrition_cat = attrition_df.dtypes[attrition_df.dtypes == "object"].index.tolist()

In [20]:
# Check the number of unique values in each column
attrition_df[attrition_cat].nunique()

Attrition         2
BusinessTravel    3
Department        3
EducationField    6
Gender            2
JobRole           9
MaritalStatus     3
Over18            1
OverTime          2
dtype: int64

In [21]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(attrition_df[attrition_cat]))

# Add the encoded variable names to the dataframe
encode_df.columns = enc.get_feature_names(attrition_cat)
encode_df.head()

,Attrition_No,Attrition_Yes,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,EducationField_Human Resources,EducationField_Life Sciences,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [22]:
# Merge one-hot encoded features and drop the originals
attrition_df = attrition_df.merge(encode_df,left_index=True, right_index=True)
attrition_df = attrition_df.drop(attrition_cat,1)
attrition_df.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,41,1102,1,2,1,1,2,94,3,2,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,49,279,8,1,1,2,3,61,2,2,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,37,1373,2,2,1,4,4,92,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,33,1392,3,4,1,5,4,56,3,1,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,27,591,2,1,1,7,1,40,3,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [23]:
# Split our preprocessed data into our features and target arrays
y = attrition_df["Attrition_Yes"].values
X = attrition_df.drop(["Attrition_Yes","Attrition_No"],1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [24]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [25]:
# Define the model - deep neural net
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  8
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 8)                 448
_________________________________________________________________
dense_1 (Dense)              (None, 5)                 45
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 6
=================================================================
Total params: 499
Trainable params: 499
Non-trainable params: 0
_________________________________________________________________

In [26]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [27]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Train on 1102 samples
Epoch 1/100
1102/1102 [==============================] - 1s 722us/sample - loss: 0.5574 - accuracy: 0.8276
Epoch 2/100
1102/1102 [==============================] - 0s 49us/sample - loss: 0.5155 - accuracy: 0.8276
Epoch 3/100
1102/1102 [==============================] - 0s 46us/sample - loss: 0.4833 - accuracy: 0.8276
Epoch 4/100
1102/1102 [==============================] - 0s 45us/sample - loss: 0.4595 - accuracy: 0.8276
Epoch 5/100
1102/1102 [==============================] - 0s 53us/sample - loss: 0.4411 - accuracy: 0.8276
Epoch 6/100
1102/1102 [==============================] - 0s 50us/sample - loss: 0.4256 - accuracy: 0.8276
Epoch 7/100
1102/1102 [==============================] - 0s 48us/sample - loss: 0.4127 - accuracy: 0.8276
Epoch 8/100
1102/1102 [==============================] - 0s 44us/sample - loss: 0.4014 - accuracy: 0.8276
Epoch 9/100
1102/1102 [==============================] - 0s 51us/sample - loss: 0.3917 - accuracy: 0.8276
Epoch 10/100
1102/1102 [==============================] - 0s 49us/sample - loss: 0.3829 - accuracy: 0.8276
Epoch 11/100
1102/1102 [==============================] - 0s 47us/sample - loss: 0.3751 - accuracy: 0.8276
Epoch 12/100
1102/1102 [==============================] - 0s 45us/sample - loss: 0.3679 - accuracy: 0.8276
Epoch 13/100
1102/1102 [==============================] - 0s 45us/sample - loss: 0.3603 - accuracy: 0.8276
Epoch 14/100
1102/1102 [==============================] - 0s 48us/sample - loss: 0.3542 - accuracy: 0.8276
Epoch 15/100
1102/1102 [==============================] - 0s 46us/sample - loss: 0.3491 - accuracy: 0.8276
Epoch 16/100
1102/1102 [==============================] - 0s 47us/sample - loss: 0.3443 - accuracy: 0.8276
Epoch 17/100
1102/1102 [==============================] - 0s 49us/sample - loss: 0.3395 - accuracy: 0.8276
Epoch 18/100
1102/1102 [==============================] - 0s 46us/sample - loss: 0.3349 - accuracy: 0.8276
Epoch 19/100
1102/1102 [==============================] - 0s 47us/sample - loss: 0.3299 - accuracy: 0.8276
Epoch 20/100
1102/1102 [==============================] - 0s 44us/sample - loss: 0.3258 - accuracy: 0.8276
Epoch 21/100
1102/1102 [==============================] - 0s 47us/sample - loss: 0.3215 - accuracy: 0.8276
Epoch 22/100
1102/1102 [==============================] - 0s 44us/sample - loss: 0.3177 - accuracy: 0.8276
Epoch 23/100
1102/1102 [==============================] - 0s 51us/sample - loss: 0.3139 - accuracy: 0.8276
Epoch 24/100
1102/1102 [==============================] - 0s 47us/sample - loss: 0.3105 - accuracy: 0.8276
Epoch 25/100
1102/1102 [==============================] - 0s 45us/sample - loss: 0.3069 - accuracy: 0.8766
Epoch 26/100
1102/1102 [==============================] - 0s 45us/sample - loss: 0.3038 - accuracy: 0.8811
Epoch 27/100
1102/1102 [==============================] - 0s 45us/sample - loss: 0.3008 - accuracy: 0.8820
Epoch 28/100
1102/1102 [==============================] - 0s 47us/sample - loss: 0.2978 - accuracy: 0.8857
Epoch 29/100
1102/1102 [==============================] - 0s 45us/sample - loss: 0.2941 - accuracy: 0.8820
Epoch 30/100
1102/1102 [==============================] - 0s 45us/sample - loss: 0.2915 - accuracy: 0.8848
Epoch 31/100
1102/1102 [==============================] - 0s 45us/sample - loss: 0.2880 - accuracy: 0.8911
Epoch 32/100
1102/1102 [==============================] - 0s 46us/sample - loss: 0.2854 - accuracy: 0.8911
Epoch 33/100
1102/1102 [==============================] - 0s 45us/sample - loss: 0.2822 - accuracy: 0.8920
Epoch 34/100
1102/1102 [==============================] - 0s 46us/sample - loss: 0.2793 - accuracy: 0.8966
Epoch 35/100
1102/1102 [==============================] - 0s 48us/sample - loss: 0.2763 - accuracy: 0.8966
Epoch 36/100
1102/1102 [==============================] - 0s 45us/sample - loss: 0.2740 - accuracy: 0.8956
Epoch 37/100
1102/1102 [==============================] - 0s 45us/sample - loss: 0.2710 - accuracy: 0.8975
Epoch 38/100
1102/1102 [==============================] - 0s 45us/sample - loss: 0.2687 - accuracy: 0.8993
Epoch 39/100
1102/1102 [==============================] - 0s 46us/sample - loss: 0.2653 - accuracy: 0.8966
Epoch 40/100
1102/1102 [==============================] - 0s 46us/sample - loss: 0.2626 - accuracy: 0.9011
Epoch 41/100
1102/1102 [==============================] - 0s 46us/sample - loss: 0.2601 - accuracy: 0.8993
Epoch 42/100
1102/1102 [==============================] - 0s 57us/sample - loss: 0.2574 - accuracy: 0.9038
Epoch 43/100
1102/1102 [==============================] - 0s 50us/sample - loss: 0.2550 - accuracy: 0.9047
Epoch 44/100
1102/1102 [==============================] - 0s 46us/sample - loss: 0.2527 - accuracy: 0.9047
Epoch 45/100
1102/1102 [==============================] - 0s 48us/sample - loss: 0.2501 - accuracy: 0.9029
Epoch 46/100
1102/1102 [==============================] - 0s 47us/sample - loss: 0.2475 - accuracy: 0.9074
Epoch 47/100
1102/1102 [==============================] - 0s 46us/sample - loss: 0.2456 - accuracy: 0.9083
Epoch 48/100
1102/1102 [==============================] - 0s 47us/sample - loss: 0.2428 - accuracy: 0.9065
Epoch 49/100
1102/1102 [==============================] - 0s 45us/sample - loss: 0.2405 - accuracy: 0.9074
Epoch 50/100
1102/1102 [==============================] - 0s 47us/sample - loss: 0.2384 - accuracy: 0.9102
Epoch 51/100
1102/1102 [==============================] - 0s 55us/sample - loss: 0.2360 - accuracy: 0.9138
Epoch 52/100
1102/1102 [==============================] - 0s 54us/sample - loss: 0.2340 - accuracy: 0.9147
Epoch 53/100
1102/1102 [==============================] - 0s 54us/sample - loss: 0.2319 - accuracy: 0.9174
Epoch 54/100
1102/1102 [==============================] - 0s 51us/sample - loss: 0.2295 - accuracy: 0.9183
Epoch 55/100
1102/1102 [==============================] - 0s 48us/sample - loss: 0.2276 - accuracy: 0.9183
Epoch 56/100
1102/1102 [==============================] - 0s 46us/sample - loss: 0.2258 - accuracy: 0.9211
Epoch 57/100
1102/1102 [==============================] - 0s 47us/sample - loss: 0.2229 - accuracy: 0.9220
Epoch 58/100
1102/1102 [==============================] - 0s 72us/sample - loss: 0.2213 - accuracy: 0.9183
Epoch 59/100
1102/1102 [==============================] - 0s 69us/sample - loss: 0.2187 - accuracy: 0.9211
Epoch 60/100
1102/1102 [==============================] - 0s 69us/sample - loss: 0.2166 - accuracy: 0.9256
Epoch 61/100
1102/1102 [==============================] - 0s 55us/sample - loss: 0.2149 - accuracy: 0.9274
Epoch 62/100
1102/1102 [==============================] - 0s 59us/sample - loss: 0.2125 - accuracy: 0.9265
Epoch 63/100
1102/1102 [==============================] - 0s 68us/sample - loss: 0.2101 - accuracy: 0.9256
Epoch 64/100
1102/1102 [==============================] - 0s 55us/sample - loss: 0.2079 - accuracy: 0.9265
Epoch 65/100
1102/1102 [==============================] - 0s 55us/sample - loss: 0.2061 - accuracy: 0.9274
Epoch 66/100
1102/1102 [==============================] - 0s 67us/sample - loss: 0.2039 - accuracy: 0.9283
Epoch 67/100
1102/1102 [==============================] - 0s 67us/sample - loss: 0.2013 - accuracy: 0.9301
Epoch 68/100
1102/1102 [==============================] - 0s 62us/sample - loss: 0.1997 - accuracy: 0.9319
Epoch 69/100
1102/1102 [==============================] - 0s 67us/sample - loss: 0.1974 - accuracy: 0.9292
Epoch 70/100
1102/1102 [==============================] - 0s 62us/sample - loss: 0.1948 - accuracy: 0.9310
Epoch 71/100
1102/1102 [==============================] - 0s 53us/sample - loss: 0.1925 - accuracy: 0.9310
Epoch 72/100
1102/1102 [==============================] - 0s 52us/sample - loss: 0.1910 - accuracy: 0.9310
Epoch 73/100
1102/1102 [==============================] - 0s 55us/sample - loss: 0.1885 - accuracy: 0.9365
Epoch 74/100
1102/1102 [==============================] - 0s 54us/sample - loss: 0.1865 - accuracy: 0.9328
Epoch 75/100
1102/1102 [==============================] - 0s 59us/sample - loss: 0.1848 - accuracy: 0.9338
Epoch 76/100
1102/1102 [==============================] - 0s 63us/sample - loss: 0.1827 - accuracy: 0.9356
Epoch 77/100

1102/1102 [==============================] - 0s 55us/sample - loss: 0.1805 - accuracy: 0.9374
Epoch 78/100
1102/1102 [==============================] - 0s 52us/sample - loss: 0.1791 - accuracy: 0.9374
Epoch 79/100
1102/1102 [==============================] - 0s 45us/sample - loss: 0.1772 - accuracy: 0.9392
Epoch 80/100
1102/1102 [==============================] - 0s 46us/sample - loss: 0.1748 - accuracy: 0.9383
Epoch 81/100
1102/1102 [==============================] - 0s 52us/sample - loss: 0.1731 - accuracy: 0.9356
Epoch 82/100
1102/1102 [==============================] - 0s 53us/sample - loss: 0.1706 - accuracy: 0.9383
Epoch 83/100
1102/1102 [==============================] - 0s 45us/sample - loss: 0.1687 - accuracy: 0.9410
Epoch 84/100
1102/1102 [==============================] - 0s 44us/sample - loss: 0.1661 - accuracy: 0.9410
Epoch 85/100
1102/1102 [==============================] - 0s 46us/sample - loss: 0.1645 - accuracy: 0.9437
Epoch 86/100
1102/1102 [==============================] - 0s 49us/sample - loss: 0.1626 - accuracy: 0.9465
Epoch 87/100
1102/1102 [==============================] - 0s 52us/sample - loss: 0.1606 - accuracy: 0.9465
Epoch 88/100
1102/1102 [==============================] - 0s 47us/sample - loss: 0.1587 - accuracy: 0.9456
Epoch 89/100
1102/1102 [==============================] - 0s 45us/sample - loss: 0.1564 - accuracy: 0.9456
Epoch 90/100
1102/1102 [==============================] - 0s 45us/sample - loss: 0.1547 - accuracy: 0.9501
Epoch 91/100
1102/1102 [==============================] - 0s 52us/sample - loss: 0.1536 - accuracy: 0.9474
Epoch 92/100
1102/1102 [==============================] - 0s 48us/sample - loss: 0.1516 - accuracy: 0.9510
Epoch 93/100
1102/1102 [==============================] - 0s 46us/sample - loss: 0.1501 - accuracy: 0.9510
Epoch 94/100
1102/1102 [==============================] - 0s 51us/sample - loss: 0.1478 - accuracy: 0.9537
Epoch 95/100
1102/1102 [==============================] - 0s 48us/sample - loss: 0.1462 - accuracy: 0.9537
Epoch 96/100
1102/1102 [==============================] - 0s 44us/sample - loss: 0.1446 - accuracy: 0.9555
Epoch 97/100
1102/1102 [==============================] - 0s 46us/sample - loss: 0.1431 - accuracy: 0.9519
Epoch 98/100
1102/1102 [==============================] - 0s 54us/sample - loss: 0.1419 - accuracy: 0.9564
Epoch 99/100
1102/1102 [==============================] - 0s 52us/sample - loss: 0.1399 - accuracy: 0.9564
Epoch 100/100
1102/1102 [==============================] - 0s 48us/sample - loss: 0.1384 - accuracy: 0.9564

In [28]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

368/1 - 0s - loss: 0.3076 - accuracy: 0.8505
Loss: 0.4517200096793797, Accuracy: 0.8505434989929199