In [1]:
# Import Dependencies
import pandas as pd

In [2]:
# File to Load
comics_path = "Resources/books_clean.csv"

# Read the modified Comic Books csv and store into Pandas DataFrame
comics_df = pd.read_csv(comics_path, encoding="utf-8")
comics_df.head()

,ISBN,Title,Other Titles,Author,All Names,Country of Publication,Place of Publication,Publisher,Publication Year
0,9780930193904,#$@&! : the official Lloyd Llewellyn collection,Official Lloyd Llewellyn collection,"Clowes, Daniel","Clowes, Daniel [person]",England ; United States of America,"London ; Seattle, Washington",Fantagraphics ; Turnaround,1997
1,9780992664220,#WhatDoYouSee? : a graphic novel anthology of ...,NaN,NaN,Fulfilling Lives (Programme) [organisation],England,Newcastle upon Tyne,Roots & Wings,2018
2,9781302903299,#takebacktheshield,NaN,"Spencer, Nick","Spencer, Nick, author [person]",United States of America,New York,Marvel Worldwide,2017
3,9781607065166,'68. Volume 1. Better run through the jungle,Better run through the jungle,"Kidwell, Mark","Fotos, Jay [person] ; Jones, Nat, 1976- [perso...",United States of America,"Berkeley, California",Image Comics,2012
4,9781600107672,'Bots of science,Trans formers ; Trans formers animated : bots ...,"Bryant, Megan E.","Robbins, Robbie [person] ; Boo, 1981- [person]...",United States of America,"San Diego, California",NaN,2010

In [3]:
# Calculate the number of unique authors in the DataFrame
author_count = len(comics_df["Author"].unique())

# Calculate the number of unique publication countries in the DataFrame
country_count = len(comics_df["Country of Publication"].unique())

# Calculate the earliest/latest year a book was published
earliest_year = comics_df["Publication Year"].min()
latest_year = comics_df["Publication Year"].max()

In [4]:
# Place all of the data found into a summary DataFrame
summary_df = pd.DataFrame({"Total Unique Authors": [author_count],
                              "Total Unique Publication Countries": country_count,
                              "Earliest Year": earliest_year,
                              "Latest Year": latest_year})
summary_df

,Total Unique Authors,Total Unique Publication Countries,Earliest Year,Latest Year
0,4249,62,1941,2021