In [1]:
%matplotlib inline
from matplotlib import pyplot as plt
from sklearn.datasets import make_regression
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv('../Resources/residential-building.csv', header=None)
df

,0,1,2,3,4,5,6,7,8,9,...,98,99,100,101,102,103,104,105,106,107
0,81,1,85,1,1,3150.0,920.0,598.5,190,1010.84,...,733.800000,815.50,1755.00,8002.0,60.74,54.26,2978.26,41407.00,601988.1,2200
1,84,1,89,4,1,7600.0,1140.0,3040.0,400,963.81,...,1143.800000,1316.30,8364.78,8393.0,90.95,89.79,11379.37,44835.00,929027.1,5000
2,78,1,81,4,1,4800.0,840.0,480.0,100,689.84,...,589.500000,765.80,1755.00,4930.0,38.70,32.04,1653.06,37933.00,377828.6,1200
3,72,2,73,2,1,685.0,202.0,13.7,20,459.54,...,197.679557,152.25,1442.31,1456.0,9.73,8.34,686.16,8194.00,122031.7,165
4,87,1,90,2,1,3000.0,800.0,1230.0,410,631.91,...,2220.600000,2244.10,9231.76,9286.0,136.60,140.20,9821.00,48260.00,1734973.5,5500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
367,83,4,86,1,20,1350.0,350.0,108.0,80,251.37,...,1082.500000,1176.50,8343.60,8382.0,87.27,85.56,10555.47,33626.25,865878.9,1100
368,81,2,82,4,20,600.0,150.0,36.0,60,299.55,...,746.800000,815.50,1755.00,8013.0,62.78,56.45,3387.72,10646.75,606524.2,740
369,84,4,86,3,20,1900.0,430.0,285.0,150,364.41,...,1424.100000,1584.30,8776.71,8799.0,101.00,101.89,13571.80,34474.50,1067772.0,860
370,82,3,84,4,20,510.0,160.0,30.6,60,245.28,...,886.400000,909.20,7930.66,8004.0,73.57,69.26,4756.68,21855.00,669640.3,1100
371,80,1,81,3,20,890.0,230.0,35.6,40,237.03,...,629.900000,764.50,1755.00,8420.0,54.62,44.79,2206.19,40234.00,629797.2,460

In [3]:
X = df.drop([107], axis=1)
y = df[107]

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
scaler = StandardScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [5]:
reg = LinearRegression().fit(X_train_scaled, y_train)
reg.score(X_test_scaled, y_test)

-9.252197708123937e+18

In [6]:
# Select the columns that have a nonzero value from the LASSO regression.
reg = Lasso(max_iter=2000).fit(X_train_scaled, y_train)

In [7]:
from sklearn.feature_selection import SelectFromModel

In [8]:
from sklearn.feature_selection import SelectFromModel
sel = SelectFromModel(reg)
sel.fit(X_train_scaled, y_train)

SelectFromModel(estimator=Lasso(alpha=1.0, copy_X=True, fit_intercept=True,
                                max_iter=2000, normalize=False, positive=False,
                                precompute=False, random_state=None,
                                selection='cyclic', tol=0.0001,
                                warm_start=False),
                max_features=None, norm_order=1, prefit=False, threshold=None)

In [9]:
X_selected_train, X_selected_test, y_train, y_test = train_test_split(sel.transform(X), y, random_state=1)
scaler = StandardScaler().fit(X_selected_train)
X_selected_train_scaled = scaler.transform(X_selected_train)
X_selected_test_scaled = scaler.transform(X_selected_test)

In [10]:
reg = LinearRegression().fit(X_selected_train_scaled, y_train)
reg.score(X_selected_test_scaled, y_test)

0.9494857525330797